/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const plastic = new THREE.MeshPhysicalMaterial({
  color: '#000',
  roughness: 0.8,
  specular: 0.5
})

const plasticGray = new THREE.MeshPhysicalMaterial({
  color: '#111',
  roughness: 0.8,
  specular: 0.5
})

const plasticCommon = {
  metalness: 0.9,
  roughness: 0.4,
  envMapIntensity: 0.9,
  clearcoat: 1,
  transparent: true,
  // transmission: .95,
  opacity: 0.5,
  reflectivity: 0.2,
  refractionRatio: 0.985,
  ior: 1.46,
  side: THREE.DoubleSide
}

const glass = new THREE.MeshPhysicalMaterial({
  metalness: 0.9,
  roughness: 0.02,
  envMapIntensity: 0.9,
  clearcoat: 1,
  transparent: true,
  // transmission: .95,
  opacity: 0.5,
  reflectivity: 0.2,
  refractionRatio: 0.985,
  ior: 1.5,
  side: THREE.DoubleSide
})

const plasticTRansparent = new THREE.MeshPhysicalMaterial(plasticCommon)

const plasticDarkTrabsparent = new THREE.MeshPhysicalMaterial({
  color: '#111',
  ...plasticCommon
})

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube002.geometry} material={plastic} />
      <mesh castShadow receiveShadow geometry={nodes.Cube002_1.geometry} material={glass} />
      <mesh castShadow receiveShadow geometry={nodes.Cube001.geometry} material={plastic} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder002.geometry} material={plasticGray} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder002_1.geometry} material={materials['METAL.004']} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder002_2.geometry} material={materials['metal.003']} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder004.geometry} material={materials['METAL.005']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube007.geometry} material={materials['Material.011']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube007_1.geometry} material={materials['Material.012']} />
      <mesh castShadow receiveShadow geometry={nodes.Small_Tupperware.geometry} material={plasticTRansparent} />
      <mesh castShadow receiveShadow geometry={nodes.chemex.geometry} material={glass}>
        <mesh castShadow receiveShadow geometry={nodes.BezierCircle.geometry} material={materials['wood.006']} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere.geometry} material={materials['wood.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder001.geometry} material={materials['wood.005']} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.Coffee_Spoon.geometry} material={materials['metal.004']} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder007.geometry} material={nodes.Cylinder007.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder007_1.geometry} material={materials['metal.005']} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder007_2.geometry} material={materials['METAL.008']} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder007_3.geometry} material={materials['Material.020']} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder010.geometry} material={plasticDarkTrabsparent} />
      <mesh castShadow receiveShadow geometry={nodes.Circle009.geometry} material={materials['Material.024']} />
      <mesh castShadow receiveShadow geometry={nodes.Circle010.geometry} material={plasticDarkTrabsparent} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder009.geometry} material={plasticTRansparent} />
      <mesh castShadow receiveShadow geometry={nodes.Dishes_Rack.geometry} material={materials['METAL.009']}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder006.geometry} material={glass} />
        <mesh castShadow receiveShadow geometry={nodes.Circle012.geometry} material={materials['WHITE plates.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane002.geometry} material={materials['metal.009']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane004_1.geometry} material={materials['Material.025']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane004_2.geometry} material={materials['Material.026']} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.Cylinder013.geometry} material={materials['WHITE plates.002']} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder013_1.geometry} material={materials['metal.006']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube001_1.geometry} material={materials['Material.019']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube001_2.geometry} material={materials['ambientCG/WoodFloor040/1K-JPG']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube001_3.geometry} material={materials['Material.021']} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder010_1.geometry} material={materials['WHITE plates.003']} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder010_2.geometry} material={materials['metal.007']} />
      <mesh castShadow receiveShadow geometry={nodes.Fridge_main.geometry} material={materials['WHITE plates.006']} />
      <mesh castShadow receiveShadow geometry={nodes.Napkins.geometry} material={nodes.Napkins.material}>
        <mesh castShadow receiveShadow geometry={nodes.Circle004.geometry} material={materials['metal.008']} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.spices.geometry} material={nodes.spices.material}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder011.geometry} material={glass} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder011_1.geometry} material={materials['WHITE plates.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder011_2.geometry} material={materials['wood.007']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder011_3.geometry} material={materials['Material.027']} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} />
      <mesh castShadow receiveShadow geometry={nodes.Plane005_1.geometry} material={materials['ambientCG/Marble009/1K-PNG.001']} />
      <mesh castShadow receiveShadow geometry={nodes.Plane005_2.geometry} material={materials['Material.028']} />
      <mesh castShadow receiveShadow geometry={nodes.Plane005_3.geometry} material={materials['metal.002']} />
      <mesh castShadow receiveShadow geometry={nodes.Plane006.geometry} material={materials['Material.029']} />
      <mesh castShadow receiveShadow geometry={nodes.Plane006_1.geometry} material={materials['Material.004']} />
      <mesh castShadow receiveShadow geometry={nodes.rug.geometry} material={materials['Material.015']} />
      <mesh castShadow receiveShadow geometry={nodes.Pipe.geometry} material={materials['metal.014']}>
        <mesh castShadow receiveShadow geometry={nodes.Circle003.geometry} material={materials['METAL.001']} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle017.geometry}
          material={materials['METAL.014']}
          position={[9.94, 0.94, 0.21]}
        />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.sink_grid.geometry} material={materials['metal.015']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube009.geometry} material={materials['Material.017']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube009_1.geometry} material={materials['Material.031']} />
      <mesh castShadow receiveShadow geometry={nodes.Plane007.geometry} material={nodes.Plane007.material} />
      <mesh castShadow receiveShadow geometry={nodes.Plane007_1.geometry} material={materials['metal.010']} />
      <mesh castShadow receiveShadow geometry={nodes.Plane007_2.geometry} material={materials['ambientCG/Marble009/1K-PNG']} />
      <mesh castShadow receiveShadow geometry={nodes.Plane007_3.geometry} material={materials['Material.016']} />
      <mesh castShadow receiveShadow geometry={nodes.Plane007_4.geometry} material={materials['metal.011']} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder003.geometry} material={glass} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder003_1.geometry} material={plasticDarkTrabsparent} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder003_2.geometry} material={materials['Material.013']} />
      <mesh castShadow receiveShadow geometry={nodes.soap_holder001.geometry} material={materials['Material.032']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube010.geometry} material={materials['WHITE plates.007']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube010_1.geometry} material={materials['Material.034']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube010_2.geometry} material={materials['metal.016']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube010_3.geometry} material={materials['METAL.010']} />
      <mesh castShadow receiveShadow geometry={nodes.stove_beaks.geometry} material={materials['METAL.003']} />
      <mesh castShadow receiveShadow geometry={nodes.stove_controllers.geometry} material={materials['METAL.011']} />
      <mesh castShadow receiveShadow geometry={nodes.coutertop.geometry} material={materials['WHITE plates.008']} />
      <mesh castShadow receiveShadow geometry={nodes.cutter.geometry} material={materials['wood.009']} />
      <mesh castShadow receiveShadow geometry={nodes.stove_tops.geometry} material={materials['METAL.013']} />
      <mesh castShadow receiveShadow geometry={nodes.plant.geometry} material={materials.Pot}>
        <mesh castShadow receiveShadow geometry={nodes.Circle014.geometry} material={materials.dirt} />
        <mesh castShadow receiveShadow geometry={nodes.NurbsPath002.geometry} material={materials['plant.003']} />
        <mesh castShadow receiveShadow geometry={nodes.NurbsPath003.geometry} material={materials['plant.004']} />
        <mesh castShadow receiveShadow geometry={nodes.NurbsPath004.geometry} material={materials['plant.005']} />
        <mesh castShadow receiveShadow geometry={nodes.NurbsPath005.geometry} material={materials['plant.006']} />
        <mesh castShadow receiveShadow geometry={nodes.NurbsPath006.geometry} material={materials['plant.002']} />
        <mesh castShadow receiveShadow geometry={nodes.NurbsPath007.geometry} material={materials['plant.001']} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.download.geometry} material={materials.download} />
      <mesh castShadow receiveShadow geometry={nodes.coaster001.geometry} material={materials['wood.013']} />
      <mesh castShadow receiveShadow geometry={nodes.Plane024.geometry} material={materials['WHITE plates.011']} />
      <mesh castShadow receiveShadow geometry={nodes.Plane024_1.geometry} material={materials['wood.016']} />
      <mesh castShadow receiveShadow geometry={nodes.cup001.geometry} material={glass} />
      <mesh castShadow receiveShadow geometry={nodes.Circle010_1.geometry} material={materials['Material.018']} />
      <mesh castShadow receiveShadow geometry={nodes.Circle010_2.geometry} material={materials['Material.033']} />
      <mesh castShadow receiveShadow geometry={nodes.cup.geometry} material={glass} />
      <mesh castShadow receiveShadow geometry={nodes.Cube017.geometry} material={materials.glass} />
      <mesh castShadow receiveShadow geometry={nodes.Cube017_1.geometry} material={materials['Material.002']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube017_2.geometry} material={materials['WHITE plates.001']} />
      <mesh castShadow receiveShadow geometry={nodes.sink.geometry} material={materials['metal.018']} />
      <mesh castShadow receiveShadow geometry={nodes.plant_bench.geometry} material={materials['wood.010']}>
        <mesh castShadow receiveShadow geometry={nodes.Cube013.geometry} material={materials['wood.011']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube014.geometry} material={materials['wood.012']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube015.geometry} material={materials.wood} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={materials['WHITE plates.009']}>
        <mesh castShadow receiveShadow geometry={nodes.Plane012_1.geometry} material={materials['Material.039']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane013_1.geometry} material={materials['Material.038']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane014_1.geometry} material={materials['Material.040']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane015.geometry} material={materials['Material.003']} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.Cube013_1.geometry} material={nodes.Cube013_1.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube013_2.geometry} material={materials['Material.041']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube013_3.geometry} material={materials['wood.002']} />
      <mesh castShadow receiveShadow geometry={nodes.coaster.geometry} material={materials['wood.014']} />
      <mesh castShadow receiveShadow geometry={nodes.Plane021.geometry} material={materials['WHITE plates.010']} />
      <mesh castShadow receiveShadow geometry={nodes.Plane021_1.geometry} material={materials['wood.015']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube021.geometry} material={materials['WHITE plates.012']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube021_1.geometry} material={materials['wood.001']} />
      <mesh castShadow receiveShadow geometry={nodes.fridge_doors.geometry} material={materials['WHITE plates.013']}>
        <mesh castShadow receiveShadow geometry={nodes.Cube003_1.geometry} material={materials['metal.012']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube004.geometry} material={materials['metal.013']} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.Cube023.geometry} material={nodes.Cube023.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube023_1.geometry} material={glass} />
      <mesh castShadow receiveShadow geometry={nodes.Cube020.geometry} material={materials['metal.022']} />
      <mesh castShadow receiveShadow geometry={nodes.plate003.geometry} material={materials['WHITE plates.016']} />
      <mesh castShadow receiveShadow geometry={nodes.Tea_Drainer.geometry} material={materials['METAL.007']}>
        <mesh castShadow receiveShadow geometry={nodes.Circle.geometry} material={materials['METAL.006']} />
        <mesh castShadow receiveShadow geometry={nodes.Circle002_1.geometry} material={materials['METAL.002']} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube012_1.geometry} material={glass} />
      <mesh castShadow receiveShadow geometry={nodes.Cube012_2.geometry} material={materials['Material.035']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube012_3.geometry} material={materials['Material.036']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube010_4.geometry} material={plastic} />
      <mesh castShadow receiveShadow geometry={nodes.Cube011_1.geometry} material={plastic} />
      <mesh castShadow receiveShadow geometry={nodes.NurbsPath008.geometry} material={materials['metal.019']} />
      <mesh castShadow receiveShadow geometry={nodes.cloth.geometry} material={materials['Material.014']} />
      <mesh castShadow receiveShadow geometry={nodes.plate.geometry} material={materials['WHITE plates.014']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube_Cube001.geometry} material={materials['wood.004']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube_Cube001_1.geometry} material={materials['metal.017']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube_Cube001_2.geometry} material={materials['METAL.012']} />
      <mesh castShadow receiveShadow geometry={nodes.plate001.geometry} material={materials['WHITE plates.015']} />
      <mesh castShadow receiveShadow geometry={nodes.plate002.geometry} material={materials['WHITE plates']} />
    </group>
  )
}

useGLTF.preload('/model.gltf')
